# Dockerfile for frontend
FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

# Install dependencies
RUN npm install
RUN npm ci

COPY . .

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]